### ISSUE TITLE
Flight Analysis Procedures Design

### ISSUE THREAD

**Issue by jrn90** [render-se/PX4-Autopilot#11]
Tracking the steps needed to get Lincoln airborne and testing with our secured firmware for Flightcore.

### @jrn90 
- [x] #12
- [x] #13
- [x] #18

### @lincolnb-rse 
- [x] Flesh out Autonomous Tests for baseline operations
- [x] #23
- [x] Firmware calibration steps
- [x] Run test  / pre flight / post flight procedures by Dennis
- [x] Create parameter dump procedures to speed up flashing

### @Spinner-99 
- [x] Retrieve some example flight analysis so we have something to compare our procedures to

### @bpmooch 
- [x] Analyze initial flight logs, write some notes on automated analysis

**Comment by bpmooch** [comment]
There was a discussion today covering what we are actually analyzing in these flight tests. We don't have our arms fully around it. In order to figure it out, we need to gather more data on what other people are doing, and run more flights to see what data we have available.  Below are some random notes from the meeting:

- GPS truth data vs flight log is one example of valuable flight analysis
- How do we define acceptable deltas in flight comparisons? How do we quantify it using standard deviation?
- Qualitative analysis is also important. How do we describe the attributes we are looking for in a flight, hard numbers aside?
- What external variables need to be tracked when analyzing a flight. Weather was the immediate call out. What metrics can we track related to weather?

**Comment by jrn90** [comment]
>     * [ ]  Automate custom firmware delivery?

Not required for this iteration. We need additional processes & hardware in place before moving forward. Should be kept on the radar for the future.

**Comment by bpmooch** [comment]
What additional processes & hardware do we need? Let's get it into a ticket

**Comment by jrn90** [comment]
@bpmooch captured in #18

**Comment by bpmooch** [comment]
* System should plot metrics alongside data of another flight
* There should be a quick summary at the top, potentially a pass/fail indicator
* Currently, gopro helmet cam is used to capture video that contains some flight relevant data (date, time, wind conditions). Would be useful to associate this video with a flight log

**Comment by lincolnb-rse** [comment]
List of graphs to be included:
Raw Acceleration
Estimator Watchdog
Thrust and Magnetic Field
GPS Noise & Jamming
GPS Uncertainty
Acceleration Power Spectral Density
Vibration Metrics

**Comment by bpmooch** [comment]
software needs to design something at this point in https://github.com/render-se/SRA/issues/59
